---
version: '3'

services:
  docker-registry-inteliome:
    image: registry:latest
    container_name: docker-registry
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./volume:/var/lib/registry

  docker-registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: docker-registry-ui
    ports:
      - 8080:80
    environment:
      # Name of the registry it wants to connect with
      ENV_DOCKER_REGISTRY_HOST: docker-registry
      # Port of the registry it can connect to
      ENV_DOCKER_REGISTRY_PORT: 5000
