version: '3.4'

services:
  nginx:
    image: nginx:1.25.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
      - 8000:8000
