name: Node.js Test and Docker Build

on:
  push:
    branches: ["main"]

jobs:

  # build:
  #   name: "Docker Build"
  #   runs-on: ubuntu-latest

  #   permissions:
  #     id-token: write
  #     contents: read

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-region: ap-south-1
  #         role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
  #         role-duration-seconds: 1200
  #         mask-aws-account-id: false

  #     - name: Login to ECR
  #       uses: docker/login-action@v1.10.0
  #       with:
  #         registry: 027187086770.dkr.ecr.ap-south-1.amazonaws.com

  #     - name: Build and push
  #       uses: docker/build-push-action@v3
  #       with:
  #         push: true
  #         tags: 027187086770.dkr.ecr.ap-south-1.amazonaws.com/onprem-react-cicd:${{ github.sha }}

  deploy:
    name: "Deploy to worker server"
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.LIS_WORKER_SERVER_PRIVATE_KEY }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: |
          ssh ${{ secrets.USER_IP }} "mkdir -p /home/palashdm2/my-new-directory"
